#!/usr/bin/env bash
git diff --name-only | grep '\.rb' | xargs rubocop --config ~/.rubocop.new.yml
git diff --name-only | grep '\.ts' | xargs tslint -c ~/tslint.new.json
git diff --name-only | grep '\.js' | xargs jshint -c ~/.jshintrc.new
