#!/usr/bin/env bash
git diff HEAD --name-only | grep '\.rb' | xargs rubocop --config ~/.rubocop.lint.yml
git diff HEAD --name-only | grep '\.ts' | xargs tslint -c ~/tslint.lint.json
git diff HEAD --name-only | grep '\.js' | xargs jshint -c ~/.jshintrc.lint
git diff HEAD --name-only | grep '\.ts' | xargs eslint -c ~/.eslintrc.lint.json
git diff HEAD --name-only | grep '\.js' | xargs eslint -c ~/.eslintrc.lint.json
